const places = [
  {
    country: "France",
    title: "Eiffel Tower",
    desc: "Iconic Paris landmark with panoramic city views.",
    map: "https://www.google.com/maps/search/?api=1&query=Eiffel+Tower+Paris",
    img: "https://images.unsplash.com/photo-1502602898657-3e91760cbb34",
  },
  {
    country: "India",
    title: "Taj Mahal",
    desc: "Marble mausoleum and symbol of love in Agra.",
    map: "https://www.google.com/maps/search/?api=1&query=Taj+Mahal+Agra",
    img: "https://images.unsplash.com/photo-1564507592333-c60657eea523",
  },
  {
    country: "USA",
    title: "Statue of Liberty",
    desc: "Symbol of freedom on Liberty Island, New York.",
    map: "https://www.google.com/maps/search/?api=1&query=Statue+of+Liberty",
    img: "https://images.unsplash.com/photo-1526772662000-3f88f10405ff",
  },
  {
    country: "Italy",
    title: "Colosseum",
    desc: "Ancient amphitheatre in Rome.",
    map: "https://www.google.com/maps/search/?api=1&query=Colosseum+Rome",
    img: "https://imgs.search.brave.com/neuwTXTbmxyv3uZy0teDWx75fzbj6PSoMpqS-p4dtZ0/rs:fit:500:0:1:0/g:ce/aHR0cHM6Ly93d3cu/cm9tZXdpc2UuY29t/L2ltYWdlcy9jb2xv/c3NldW0tdXAtY2xv/c2UtZ3JvdW5kLWxl/dmVsLWR1c2stc21h/bGwuanBlZw",
  },
  {
    country: "China",
    title: "Great Wall of China",
    desc: "One of the longest man-made structures in the world.",
    map: "https://www.google.com/maps/search/?api=1&query=Great+Wall+of+China",
    img: "https://images.unsplash.com/photo-1508804185872-d7badad00f7d",
  },
  {
    country: "Brazil",
    title: "Christ the Redeemer",
    desc: "Statue overlooking Rio de Janeiro.",
    map: "https://www.google.com/maps/search/?api=1&query=Christ+the+Redeemer+Rio",
    img: "https://imgs.search.brave.com/IxQDKGoYUg97lBEPpiAYtK93MlfXJn1I0KQa2x5iUh8/rs:fit:500:0:1:0/g:ce/aHR0cHM6Ly93YWxs/cGFwZXJjYXZlLmNv/bS93cC93cDE5OTE2/ODUuanBn",
  },
  {
    country: "Australia",
    title: "Sydney Opera House",
    desc: "Architectural masterpiece on Sydney Harbour.",
    map: "https://www.google.com/maps/search/?api=1&query=Sydney+Opera+House",
    img: "https://images.unsplash.com/photo-1506973035872-a4ec16b8e8d9",
  },
  {
    country: "Egypt",
    title: "Pyramids of Giza",
    desc: "Ancient wonders built as tombs for pharaohs.",
    map: "https://www.google.com/maps/search/?api=1&query=Pyramids+of+Giza",
    img: "https://images.unsplash.com/photo-1539650116574-8efeb43e2750",
  },
  {
    country: "UK",
    title: "Big Ben",
    desc: "Historic clock tower in London.",
    map: "https://www.google.com/maps/search/?api=1&query=Big+Ben+London",
    img: "https://imgs.search.brave.com/bHjfXfVhRONZ3RWKiWDJuetfnAVqcidYVc7TVi2Ojf4/rs:fit:500:0:1:0/g:ce/aHR0cHM6Ly9jZG4u/cGl4YWJheS5jb20v/cGhvdG8vMjAxOS8x/Mi8yOS8yMS8yMS9i/aWctYmVuLTQ3Mjgx/OTlfNjQwLmpwZw",
  },
  {
    country: "USA",
    title: "Golden Gate Bridge",
    desc: "Iconic bridge in San Francisco.",
    map: "https://www.google.com/maps/search/?api=1&query=Golden+Gate+Bridge",
    img: "https://images.unsplash.com/photo-1501594907352-04cda38ebc29",
  },
  {
    country: "Peru",
    title: "Machu Picchu",
    desc: "Ancient Incan city in the Andes.",
    map: "https://www.google.com/maps/search/?api=1&query=Machu+Picchu",
    img: "https://imgs.search.brave.com/yvKDXAY3Dl5qzIDeRuzunT0tn5BttnsVprLLYL2K9po/rs:fit:500:0:1:0/g:ce/aHR0cHM6Ly9pLm5h/dGdlb2ZlLmNvbS9u/LzgxOWVhNzc0LWFh/ODAtNDM1ZS1hZjVh/LWFlNTZlZmVlN2Nl/My85MjQ5MS5qcGc",
  },
  {
    country: "Spain",
    title: "Sagrada Familia",
    desc: "Gaudí’s famous basilica in Barcelona.",
    map: "https://www.google.com/maps/search/?api=1&query=Sagrada+Familia",
    img: "https://images.unsplash.com/photo-1528909514045-2fa4ac7a08ba",
  },
  {
    country: "Mexico",
    title: "Chichen Itza",
    desc: "Mayan archaeological site in Yucatán.",
    map: "https://www.google.com/maps/search/?api=1&query=Chichen+Itza",
    img: "https://imgs.search.brave.com/4tfccDNw-W9q99VYsv-aJq0uLCPb_xV4ZBRVA00lTeY/rs:fit:500:0:1:0/g:ce/aHR0cHM6Ly93d3cu/Y2hpY2hlbml0emEu/Y29tL3B1YmxpYy9h/c3NldHMvaW1nL3By/aXZhdGUtY2hpY2hl/bi1pdHphLXRvdXIu/anBn",
  },
  {
    country: "Greece",
    title: "Acropolis",
    desc: "Ancient citadel above Athens.",
    map: "https://www.google.com/maps/search/?api=1&query=Acropolis+Athens",
    img: "https://imgs.search.brave.com/-YGdqynx-8mbqDEPtZIIVk72EFC237U120ennfcsmSM/rs:fit:500:0:1:0/g:ce/aHR0cHM6Ly90NC5m/dGNkbi5uZXQvanBn/LzA0Lzk0LzM3LzU5/LzM2MF9GXzQ5NDM3/NTk5Ml8yMnRHOXV1/akhqMWw0cllIVWhU/Vm5KbHFoczJRUExp/cC5qcGc",
  },
  {
    country: "Japan",
    title: "Mount Fuji",
    desc: "Natural beauty and Japan’s tallest peak.",
    map: "https://www.google.com/maps/search/?api=1&query=Mount+Fuji",
    img: "https://images.unsplash.com/photo-1549693578-d683be217e58",
  },
  {
    country: "Canada",
    title: "Niagara Falls",
    desc: "Famous waterfalls on the USA–Canada border.",
    map: "https://www.google.com/maps/search/?api=1&query=Niagara+Falls",
    img: "https://imgs.search.brave.com/D6Ns3ByB1iEzfuwKO_lMJzo5F0UD_Z8peTB9oPOqRy4/rs:fit:500:0:1:0/g:ce/aHR0cHM6Ly9tZWRp/YS5nZXR0eWltYWdl/cy5jb20vaWQvMTI0/NTg0MTI3OC9waG90/by9uaWFnYXJhLWZh/bGxzLW5ldy15b3Jr/LWFuLWFlcmlhbC12/aWV3LW9mLXRoZS1w/YXJ0aWFsbHktZnJv/emVuLW5pYWdhcmEt/ZmFsbHMtd2hpY2gt/aXMtb24tdGhlLmpw/Zz9zPTYxMng2MTIm/dz0wJms9MjAmYz1k/RHJ6enpzRi1vN0Qw/WnEtQXctejlxSGdO/X3JKZVRFaGNpYVlw/dTNseHFZPQ",
  },
  {
    country: "UAE",
    title: "Burj Khalifa",
    desc: "The tallest building in the world.",
    map: "https://www.google.com/maps/search/?api=1&query=Burj+Khalifa",
    img: "https://images.unsplash.com/photo-1526495124232-a04e1849168c",
  },
  {
    country: "Turkey",
    title: "Hagia Sophia",
    desc: "Historic architectural wonder in Istanbul.",
    map: "https://www.google.com/maps/search/?api=1&query=Hagia+Sophia+Istanbul",
    img: "https://imgs.search.brave.com/gLbaWYeZ9XpvV5kRKnjdmI7ToGA64sN4vNONWaHkQH8/rs:fit:500:0:1:0/g:ce/aHR0cHM6Ly9zdGF0/aWMudmVjdGVlenku/Y29tL3N5c3RlbS9y/ZXNvdXJjZXMvdGh1/bWJuYWlscy8wMTAv/ODkwLzE4MC9zbWFs/bC9oYWdpYS1zb3Bo/aWEtaW4taXN0YW5i/dWwtdHVya2V5LXBo/b3RvLmpwZw",
  },
  {
    country: "Italy",
    title: "Leaning Tower of Pisa",
    desc: "Famous leaning bell tower.",
    map: "https://www.google.com/maps/search/?api=1&query=Leaning+Tower+of+Pisa",
    img: "https://imgs.search.brave.com/4c3lUFQrSWDLDuDbejPbMGDQyxZoo7boaXf29nUNzj8/rs:fit:500:0:1:0/g:ce/aHR0cHM6Ly9oYmxp/bWcubW10Y2RuLmNv/bS9jb250ZW50L2h1/YmJsZS9pbWcvZmxv/cmVuY2VkZXN0aW1h/Z2VzL21tdC9hY3Rp/dml0aWVzL21fTGVh/bmluZ19Ub3dlcl9v/Zl9QaXNhXzJfbF82/NjdfMTAwMC5qcGc",
  },
  {
    country: "France",
    title: "Louvre Museum",
    desc: "World’s largest art museum.",
    map: "https://www.google.com/maps/search/?api=1&query=Louvre+Museum+Paris",
    img: "https://imgs.search.brave.com/DKis_-A96Jy532vGGmIGfMothUGhO4rV14hm3U_hApY/rs:fit:500:0:1:0/g:ce/aHR0cHM6Ly90My5m/dGNkbi5uZXQvanBn/LzAzLzEwLzYxLzM0/LzM2MF9GXzMxMDYx/MzQ1OF9rSVFyY3kz/dWgwNnJWVmE5QmNG/eU9PR1c0a0ttWkZ4/QS5qcGc",
  },
  /* … (continue with 30+ more below) */
  {
    country: "Nepal",
    title: "Mount Everest",
    desc: "Highest mountain on Earth.",
    map: "https://www.google.com/maps/search/?api=1&query=Mount+Everest",
    img: "https://imgs.search.brave.com/60k9IMHoSbQirkzHUzlfhx_zgU0g7Sm8DQGpM8DJ99w/rs:fit:500:0:1:0/g:ce/aHR0cHM6Ly9tZWRp/YS5nZXR0eWltYWdl/cy5jb20vaWQvMTQ4/NjAyNjkwMi9waG90/by9hZXJpYWwtdmll/dy1vZi1tb3VudC1l/dmVyZXN0LWFuZC1o/aW1hbGF5YS1tb3Vu/dGFpbnMtbmVwYWwu/anBnP3M9NjEyeDYx/MiZ3PTAmaz0yMCZj/PXFRYVRtZ0JfRWZo/V3ZrVFJZZmhyakpT/NE9tX2V2eVB4MTVj/ZjZVNDVJUDA9",
  },
  {
    country: "UK",
    title: "Stonehenge",
    desc: "Prehistoric stone circle.",
    map: "https://www.google.com/maps/search/?api=1&query=Stonehenge",
    img: "https://imgs.search.brave.com/wAN1jR4ZVGDLUTqmo9bTXnxIi5aV1ay8ux96Xfqfexw/rs:fit:500:0:1:0/g:ce/aHR0cHM6Ly9ucHIu/YnJpZ2h0c3BvdGNk/bi5jb20vZGltczMv/ZGVmYXVsdC9zdHJp/cC9mYWxzZS9jcm9w/LzUzNzd4MzAyNCsw/KzAvcmVzaXplLzEx/MDAvcXVhbGl0eS81/MC9mb3JtYXQvanBl/Zy8_dXJsPWh0dHA6/Ly9ucHItYnJpZ2h0/c3BvdC5zMy5hbWF6/b25hd3MuY29tLzU1/L2NiL2VkYTcwYjY3/NDg0ODg5NzBlNGIx/YzliODQwMGQvZ2V0/dHlpbWFnZXMtMTIz/ODIyMjQxOC5qcGc",
  },
  {
    country: "Brazil",
    title: "Amazon Rainforest",
    desc: "Lush tropical rainforest.",
    map: "https://www.google.com/maps/search/?api=1&query=Amazon+Rainforest",
    img: "https://imgs.search.brave.com/mswfbsTJvypfLVgoQtPkd2IoU_E4UParB4tkbWtCuy0/rs:fit:500:0:1:0/g:ce/aHR0cHM6Ly9tZWRp/YS5nZXR0eWltYWdl/cy5jb20vaWQvMjIy/NjIxMTQxNy9waG90/by9hZXJpYWwtdmll/dy1vZi10aGUtbWVh/bmRlcmluZy1wYXBh/Z2Fpby1yaXZlci1h/bmQtc3Vycm91bmRp/bmctYW1hem9uLXJh/aW5mb3Jlc3Qtb2Yt/dGhlLWphdS5qcGc_/cz02MTJ4NjEyJnc9/MCZrPTIwJmM9TXhF/eENmOS1VZE42aWRl/SkF1d05IY3U5LWt3/b0VJOVZZMDFZc1ZG/a1pXMD0",
  },
  {
    country: "USA",
    title: "Yellowstone National Park",
    desc: "Famous geothermal features and wildlife.",
    map: "https://www.google.com/maps/search/?api=1&query=Yellowstone+National+Park",
    img: "https://images.unsplash.com/photo-1508804185872-d7badad00f7d",
  },
 
  

];


export default places